version: 2
jobs:
  build:
    working_directory: ~/gradle-build
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run: chmod +x gradlew
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: |
            ./gradlew -v
            ./gradlew jar
      - save_cache:
           paths:
              - ~/.gradle
           key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
      - deploy:
          command: |
            ./gradlew publishPlugins