version: 2
jobs:
  build:
    docker:
      - image: airdock/oracle-jdk
    steps:
      - checkout
      - run: ./gradlew jar
      - store_artifacts:
          path: build/libs
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
      - deploy:
          command: |
            ./gradlew publish
