version: 2
jobs:
  build:
    docker:
      - image: airdock/oracle-jdk
    steps:
      - checkout
      - run: chmod +x gradlew
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: ./gradlew jar
      - save_cache:
           paths:
              - ~/.gradle
           key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
